# Generated by Django 5.0.6 on 2024-06-20 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ManyToManyField(related_name='refereed_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
